#
# RaspberryPi GPIO mappings
#


# sensors
ABSOLUTE_SWITCH_PIN = 23
CONTACT_SWITCH_PIN = 24  # Todo: define this
ENCODER_A_PLUS_PIN = 16
ENCODER_B_PLUS_PIN = 18
PRESSURE_SENSOR_PIN = 0 # Todo: define this
BUZZER_PIN = 25
POWER_SWITCH_PIN = 17
# FLOW_SENSOR_PIN = 0
