# position constants
BAG_CLEAR_TOL = 0   # TODO
ENCODER_ONE_ROTATION = 400
TIC_ONE_ROTATION = 12800

# motion constants
HOMING_VELOCITY = 4000000
VELOCITY_FACTOR = 1/12

# time constants (s)
MIN_EXP_PAUSE = 0   # TODO
INSP_HOLD_DUR = 0   # TODO
MAX_EXP_DUR = 0     # TODO

# safety constants
MAX_PRESSURE = 40.0         # TODO
MIN_PLATEAU_PRESSURE = 5.0  # TODO
MAX_RESIST_PRESSURE = 2.0   # TODO
MIN_TIDAL_PRESSURE = 5.0    # TODO
VOLUME_ERROR_THRESH = 50.0  # TODO
# MAX_MOTOR_CURRENT = 0     # TODO
MECHANICAL_TIMEOUT = 1.0    # TODO
