# position constants
BAG_CLEAR_TOL = 0   # TODO
ENCODER_ONE_ROTATION = 400
TIC_ONE_ROTATION = 12800

# motion constants
HOMING_VELOCITY = 40000000
VELOCITY_FACTOR = 2/12
TV_PULLEY_CONVERT_FACTOR = 0.0016  # 0.8 rotation to 500ml ratio (0.8/800)

# time constants (s)
MIN_EXP_PAUSE = 0.025   # TODO
INSP_HOLD_DUR = 0.025   # TODO
MAX_EXP_DUR = 4     # TODO

# safety constants
MAX_PRESSURE = 40.0         # TODO
MIN_PLATEAU_PRESSURE = 5.0  # TODO
MAX_RESIST_PRESSURE = 2.0   # TODO
MIN_TIDAL_PRESSURE = 5.0    # TODO
VOLUME_ERROR_THRESH = 50.0  # TODO
# MAX_MOTOR_CURRENT = 0     # TODO
MECHANICAL_TIMEOUT = 1.0    # TODO

TIDAL_VOLUME_MAX = 500
TIDAL_VOLUME_MIN = 0